name: "aMule"
description: "Cliente eD2k/Kad con interfaz web integrada en Home Assistant"
version: "1.2.0"
slug: "amule_addon"
url: "https://github.com/GazKez/Gazlaxy-s-Addons/tree/main/amule"

arch:
  - amd64

startup: services
boot: auto
init: false
backup: cold

ingress: true
ingress_port: 4711
ingress_entry: "/"
panel_icon: "mdi:download-network"
panel_title: "aMule"
panel_admin: true

ports:
  4711/tcp: null
  4712/tcp: null
  4662/tcp: 4662
  4665/udp: 4665
  4672/udp: 4672

ports_description:
  4711/tcp: "Interfaz web (normalmente se accede mediante Ingress)"
  4712/tcp: "Conexiones externas para amulegui y amulecmd"
  4662/tcp: "Tráfico eD2k entre clientes"
  4665/udp: "Búsquedas globales eD2k"
  4672/udp: "Protocolo eMule extendido y red Kad"

map:
  - type: media
    read_only: false
  - type: share
    read_only: false

options:
  puid: 1000
  pgid: 1000
  umask: "0002"
  tz: "Europe/Madrid"
  gui_pwd: null
  webui_pwd: null
  webui_theme: "responsive"
  incoming_dir: "/media/amule/incoming"
  temp_dir: "/media/amule/temp"
  fix_permissions: true
  mod_auto_restart_enabled: true
  mod_auto_restart_cron: "0 6 * * *"
  mod_auto_share_enabled: false
  mod_auto_share_directories: "/media/amule/incoming"

schema:
  puid: "int(0,)"
  pgid: "int(0,)"
  umask: "match(^0[0-7]{3}$)"
  tz: str
  gui_pwd: password
  webui_pwd: password
  webui_theme: "list(responsive|default)"
  incoming_dir: "match(^/(media|share)/.+$)"
  temp_dir: "match(^/(media|share)/.+$)"
  fix_permissions: bool
  mod_auto_restart_enabled: bool
  mod_auto_restart_cron: str
  mod_auto_share_enabled: bool
  mod_auto_share_directories: str

watchdog: "tcp://[HOST]:[PORT:4711]"

image: "ghcr.io/gazkez/{arch}-addon-amule"
