name: "Gazlaxy AceServe"
version: "0.1.0"
slug: "gazlaxy_aceserve"

description: "AceStream Engine with HTTPAceProxy for Home Assistant"

url: "https://github.com/GazKez/Gazlaxy-s-Addons"

arch:
  - amd64

startup: services
boot: auto
init: false

ports:
  6878/tcp: 6878
  8621/tcp: 8621
  62062/tcp: 62062
  8888/tcp: 8888

ports_description:
  6878/tcp: "AceStream HTTP"
  8621/tcp: "AceStream P2P"
  62062/tcp: "AceStream API"
  8888/tcp: "HTTPAceProxy"

options:
  max_connections: 10
  max_concurrent_channels: 5

schema:
  max_connections: int(1,100)
  max_concurrent_channels: int(1,50)

map:
  - addon_config:rw
